apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-test-simple
  namespace: test-simple
  labels:
    app: pod-test-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test-simple
  template:
    metadata:
      labels:
        app: pod-test-simple
    spec:
      containers:
      - name: pod-test-simple
        image: nginx:1.23.1-alpine
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        volumeMounts:
          - name: nginx-configuration
            mountPath: /etc/nginx/nginx.conf
            subPath: NGINX_CONF_KEY
          - name: application-configuration
            mountPath: /etc/nginx/nginx.d/app.conf
            subPath: APP_CONF_KEY
          - name: application-html
            mountPath: /usr/share/nginx/html/index.html
            subPath: APP_HTML_KEY
      volumes:
        - name: nginx-configuration
          secret:
            secretName: pod-secret-simple
        - name: application-configuration
          secret:
            secretName: pod-secret-simple
        - name: application-html
          secret:
            secretName: pod-secret-simple
