apiVersion: v1
kind: Service
metadata:
  name: pod-test-service
  namespace: test-simple
spec:
  selector:
    app: pod-test-simple
  ports:
    - name: http
      protocol: TCP
      port: 4321
      targetPort: 4321
