apiVersion: v1
kind: Secret
metadata:
  name: pod-sso-gatekeeper-secret
  namespace: pod-sso
  labels:
    app: pod-sso-gatekeeper
type: Opaque
stringData:
    # OIDC Config
    OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
    OAUTH2_PROXY_OIDC_ISSUER_URL: "https://keycloak.kube.local:8443/realms/sso"
    OAUTH2_PROXY_CLIENT_ID: "simple"
    OAUTH2_PROXY_CLIENT_SECRET: "aifWG2l5c3ltImMSrwl5dmCb8V6xsjxq"
    # Cookie Config
    OAUTH2_PROXY_COOKIE_SECRET: "d3c1VGxTZmtwQzBURUFMZklVMXZUakZ2"
    OAUTH2_PROXY_COOKIE_HTTPONLY: "true"
    OAUTH2_PROXY_COOKIE_SECURE: "true"
    OAUTH2_PROXY_COOKIE_DOMAINS: "*"
    OAUTH2_PROXY_COOKIE_REFRESH: "30m"
    OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
    OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
    OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"
    # Proxy config
    OAUTH2_PROXY_EMAIL_DOMAINS: "*"
    OAUTH2_PROXY_WHITELIST_DOMAINS: "*"
    OAUTH2_PROXY_HTTPS_ADDRESS: "0.0.0.0:8765"
    OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
    OAUTH2_PROXY_REVERSE_PROXY: "true"
    OAUTH2_PROXY_UPSTREAMS: "https://pod-sso-nginx-service.pod-sso.svc.cluster.local:8765"
    OAUTH2_PROXY_REDIRECT_URL: "https://simple.kube.local/oauth2/callback"
    #OAUTH2_PROXY_ALLOWED_GROUPS: "simple"
    # CA / CERT config
    OAUTH2_PROXY_PROVIDER_CA_FILE: "/certs/ca.pem"
    OAUTH2_PROXY_TLS_CERT_FILE: "/certs/cert.pem"
    OAUTH2_PROXY_TLS_KEY_FILE: "/certs/cert.key"
    OAUTH2_PROXY_TLS_MIN_VERSION: "TLS1.2"
    OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
    OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: "true"
    #
    #OAUTH2_PROXY_SCOPE: "openid"
    #OAUTH2_PROXY_PROXY_PREFIX: "/oauth2"
    #OAUTH2_PROXY_LOGIN_URL: "https://keycloak.kube.local/realms/sso/protocol/openid-connect/auth"
    #OAUTH2_PROXY_REDEEM_URL: "https://keycloak.kube.local/realms/sso/protocol/openid-connect/token"
    #OAUTH2_PROXY_VALIDATE_URL: "https://keycloak.kube.local/realms/sso/protocol/openid-connect/userinfo"
    #OAUTH2_PROXY_REDIRECT_URL: "https://simple.kube.local"
    #OAUTH2_PROXY_SKIP_AUTH_PREFLIGHT: "true"
    #OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
    #OAUTH2_PROXY_SKIP_AUTH_ROUTES: "GET: /schema.json"
    #OAUTH2_PROXY_STANDARD_LOGGING: "true"
    #OAUTH2_PROXY_AUTH_LOGGING: "true"
    #OAUTH2_PROXY_REQUEST_LOGGING: "true"
    #OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
    #OAUTH2_PROXY_OIDC_JWKS_URL: "https://keycloak.kube.local/realms/sso/protocol/openid-connect/certs"
    #OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"
    #OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
