apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-test-longhorn-pvc
  namespace: test-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
