apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-test-ingress-pvc
  namespace: test-ingress
  labels:
    app: pod-test-ingress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
